name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0' # Tumhari Flutter version

      - name: Regenerate project (ensure Gradle files exist)
        run: flutter create .

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release

      # ✅ Direct Actions logs se download karne ke liye
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mymusic_pro-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # ✅ GitHub Release pe bhi upload hoga (optional)
      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
