name: Regenerate Android

on:
  workflow_dispatch: # This lets you run the workflow manually from the Actions tab

jobs:
  regenerate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'   # Change this if your Flutter version is different

      - name: Regenerate Android folder
        run: flutter create .

      - name: Commit and Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add android
          git commit -m "Regenerate Android folder via workflow" || echo "No changes to commit"
          git push
